contrat_homepage:
    path:     /
    defaults: { _controller: ContratBundle:Default:index }

affiche:
    path:     /afficheC
    defaults: { _controller: ContratBundle:Contrat:afficheC }
ajout:
    path:     /ajouterContrat
    defaults: { _controller: ContratBundle:Contrat:AjouterC }
