contrat_homepage:
    path:     /
    defaults: { _controller: ContratBundle:Default:index }

ajouter_contrat:
    path:     /ajouterContrat
    defaults: { _controller: ContratBundle:Contrat:ajouterContrat }

ajoutusersucces:
    path:     /ajoutSuccess
    defaults: { _controller: ContratBundle:Contrat:afficherSuccess }
