contrat_homepage:
    path:     /
    defaults: { _controller: ContratBundle:Default:index }

ajouter_contrat:
    path:     /ajouterContrat/{id_type}/{typecon}/{prime}
    defaults: { _controller: ContratBundle:Contrat:ajouterContrat }

ajoutsucces:
    path:     /ajoutSuccess
    defaults: { _controller: ContratBundle:Contrat:afficherSuccess }

affichercontratpart:
    path:     /afficherContratPart/{cin}
    defaults: { _controller: ContratBundle:Contrat:AfficherContratParticulier }

affichercontratentr:
    path:     /afficherContratEntr/{nom}
    defaults: { _controller: ContratBundle:Contrat:AfficherContratEntreprise }
