assure_particulier_homepage:
    path:     /
    defaults: { _controller: AssureParticulierBundle:Default:index }
ajouter_asspart:
    path:     /creerProfile
    defaults: { _controller: AssureParticulierBundle:AssureParticulier:ajouterAssPart }

redirect_choixprofile:
    path:     /ChoixProfile
    defaults: { _controller: AssureParticulierBundle:AssureParticulier:redirectPartForm }
modifierprofilepart:
    path:     /ModifierProfile/{email}
    defaults: { _controller: AssureParticulierBundle:AssureParticulier:modifierPart }

profile:
    path:     /afficherProfile
    defaults: { _controller: AssureParticulierBundle:AssureParticulier:AssPartProfileDashboard }

showprofile:
    path:     /afficherProfile
    defaults: { _controller: AssureParticulierBundle:AssureParticulier:showProfile }

